name: idk

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-this:
    runs-on: ubuntu-latest
    steps:
      - name: idk what to name
        run: echo "hi"
